### ISSUE TITLE
Use icons and fonts

### ISSUE THREAD

**Issue by Abeera-Tariq** [ammarazahid/mokup-23-hakaton#1]
It is always a good practice to make use of icons and fonts wherever possible to generate a pixel perfect page. Avoid using cropped images. 

![image](https://user-images.githubusercontent.com/35397213/58506248-485c2d00-81a8-11e9-9747-99c79ace9da2.png)

https://github.com/ammarazahid/mokup-23-hakaton/blob/8089e035caaebbe24bbe20fbd2efd9e28c9cab81/index.html#L18-L22

This section can be created using fonts and icons and then applying css rules for border-radius, height/width etc.

**Comment by ammarazahid** [comment]
mam miss ne to kaha tha k inki ap image se cut kr k lga skte

**Comment by Abeera-Tariq** [comment]
@KhairUnNisa10 batayingi kyunke mei uss waqt class mei nahi thi.
Agar unhone kaha tha tou phr masla nae.

**Comment by KhairUnNisa10** [comment]
Ammara, As the deadline has been increased and you have more time. Don't make this section with cropped images, make this using div.

**Comment by ammarazahid** [comment]
Mam, where???
