### ISSUE TITLE
Units of Size

### ISSUE THREAD

**Issue by Abeera-Tariq** [ammarazahid/mokup-23-hakaton#3]
https://github.com/ammarazahid/mokup-23-hakaton/blob/8089e035caaebbe24bbe20fbd2efd9e28c9cab81/style.css#L110-L118
This is a very minor issue. Although there is no problem here since the value is 0. However, in case of a non-zero value, missing the unit might cause the browser to be confused and behave differently. Therefore, try not skip units of size. Instead of just "0" write "0px". 

If you understand the importance of writing units, ignore this issue :)

**Comment by ammarazahid** [comment]
done mam #3
